apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- extension.yaml

patches:
- patch: |
    - op: replace
      path: /spec/deployment/extension/helm/ociRepository/ref
      value: local-skaffold/gardener-extension-diki/charts/extension
  target:
    group: operator.gardener.cloud
    kind: Extension
    name: extension-diki
