//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-diki/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefaultScheduledScanSpec)(nil), (*config.DefaultScheduledScanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefaultScheduledScanSpec_To_config_DefaultScheduledScanSpec(a.(*DefaultScheduledScanSpec), b.(*config.DefaultScheduledScanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DefaultScheduledScanSpec)(nil), (*DefaultScheduledScanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DefaultScheduledScanSpec_To_v1alpha1_DefaultScheduledScanSpec(a.(*config.DefaultScheduledScanSpec), b.(*DefaultScheduledScanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetConfig)(nil), (*config.RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetConfig_To_config_RulesetConfig(a.(*RulesetConfig), b.(*config.RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RulesetConfig)(nil), (*RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RulesetConfig_To_v1alpha1_RulesetConfig(a.(*config.RulesetConfig), b.(*RulesetConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.BaseDikiConfig = (*string)(unsafe.Pointer(in.BaseDikiConfig))
	out.DefaultScheduledScan = (*config.DefaultScheduledScanSpec)(unsafe.Pointer(in.DefaultScheduledScan))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.BaseDikiConfig = (*string)(unsafe.Pointer(in.BaseDikiConfig))
	out.DefaultScheduledScan = (*DefaultScheduledScanSpec)(unsafe.Pointer(in.DefaultScheduledScan))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_DefaultScheduledScanSpec_To_config_DefaultScheduledScanSpec(in *DefaultScheduledScanSpec, out *config.DefaultScheduledScanSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.SuccessfulScansHistoryLimit = (*int32)(unsafe.Pointer(in.SuccessfulScansHistoryLimit))
	out.FailedScansHistoryLimit = (*int32)(unsafe.Pointer(in.FailedScansHistoryLimit))
	out.Rulesets = *(*[]config.RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_v1alpha1_DefaultScheduledScanSpec_To_config_DefaultScheduledScanSpec is an autogenerated conversion function.
func Convert_v1alpha1_DefaultScheduledScanSpec_To_config_DefaultScheduledScanSpec(in *DefaultScheduledScanSpec, out *config.DefaultScheduledScanSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefaultScheduledScanSpec_To_config_DefaultScheduledScanSpec(in, out, s)
}

func autoConvert_config_DefaultScheduledScanSpec_To_v1alpha1_DefaultScheduledScanSpec(in *config.DefaultScheduledScanSpec, out *DefaultScheduledScanSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.SuccessfulScansHistoryLimit = (*int32)(unsafe.Pointer(in.SuccessfulScansHistoryLimit))
	out.FailedScansHistoryLimit = (*int32)(unsafe.Pointer(in.FailedScansHistoryLimit))
	out.Rulesets = *(*[]RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_config_DefaultScheduledScanSpec_To_v1alpha1_DefaultScheduledScanSpec is an autogenerated conversion function.
func Convert_config_DefaultScheduledScanSpec_To_v1alpha1_DefaultScheduledScanSpec(in *config.DefaultScheduledScanSpec, out *DefaultScheduledScanSpec, s conversion.Scope) error {
	return autoConvert_config_DefaultScheduledScanSpec_To_v1alpha1_DefaultScheduledScanSpec(in, out, s)
}

func autoConvert_v1alpha1_RulesetConfig_To_config_RulesetConfig(in *RulesetConfig, out *config.RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_RulesetConfig_To_config_RulesetConfig is an autogenerated conversion function.
func Convert_v1alpha1_RulesetConfig_To_config_RulesetConfig(in *RulesetConfig, out *config.RulesetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetConfig_To_config_RulesetConfig(in, out, s)
}

func autoConvert_config_RulesetConfig_To_v1alpha1_RulesetConfig(in *config.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	return nil
}

// Convert_config_RulesetConfig_To_v1alpha1_RulesetConfig is an autogenerated conversion function.
func Convert_config_RulesetConfig_To_v1alpha1_RulesetConfig(in *config.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	return autoConvert_config_RulesetConfig_To_v1alpha1_RulesetConfig(in, out, s)
}
