apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: extension
build:
  tagPolicy:
    envTemplate:
      template: "{{.EFFECTIVE_VERSION}}"
  artifacts:
    - image: local-skaffold/gardener-extension-diki
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-diki
            - cmd/gardener-extension-diki/app
            - pkg/cmd
            - pkg/constants
            - pkg/controller/lifecycle
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-diki
    - image: local-skaffold/gardener-extension-diki/charts/extension
      custom:
        buildCommand: |
          bash "$GARDENER_HACK_DIR/push-helm.sh" ./charts/gardener-extension-diki .image.ref
        dependencies:
          paths:
            - charts/gardener-extension-diki
      requires:
        - image: local-skaffold/gardener-extension-diki
          alias: IMG
  insecureRegistries:
    - registry.local.gardener.cloud:5001
manifests:
  kustomize:
    paths:
      - example
deploy:
  kubectl: {}
resourceSelector:
  allow:
    - groupKind: Extension.operator.gardener.cloud
      image:
        - .spec.deployment.extension.helm.ociRepository.ref
