//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.BaseDikiConfig != nil {
		in, out := &in.BaseDikiConfig, &out.BaseDikiConfig
		*out = new(string)
		**out = **in
	}
	if in.DefaultScheduledScan != nil {
		in, out := &in.DefaultScheduledScan, &out.DefaultScheduledScan
		*out = new(DefaultScheduledScanSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultScheduledScanSpec) DeepCopyInto(out *DefaultScheduledScanSpec) {
	*out = *in
	if in.SuccessfulScansHistoryLimit != nil {
		in, out := &in.SuccessfulScansHistoryLimit, &out.SuccessfulScansHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedScansHistoryLimit != nil {
		in, out := &in.FailedScansHistoryLimit, &out.FailedScansHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Rulesets != nil {
		in, out := &in.Rulesets, &out.Rulesets
		*out = make([]RulesetConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultScheduledScanSpec.
func (in *DefaultScheduledScanSpec) DeepCopy() *DefaultScheduledScanSpec {
	if in == nil {
		return nil
	}
	out := new(DefaultScheduledScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetConfig) DeepCopyInto(out *RulesetConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetConfig.
func (in *RulesetConfig) DeepCopy() *RulesetConfig {
	if in == nil {
		return nil
	}
	out := new(RulesetConfig)
	in.DeepCopyInto(out)
	return out
}
