apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-diki
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  resources:
  - kind: Extension
    type: diki
    lifecycle:
      reconcile: AfterKubeAPIServer
      delete: BeforeKubeAPIServer
      migrate: AfterKubeAPIServer
